### ISSUE TITLE
Month tab is usually wrong

### ISSUE THREAD

**Issue by mwsasser** [jlx84/lightning-calendar-tabs#4]
When I select `Today` the calendar itself is correct but the month tab is last month.

The bug started around Thunderbird 52.4.0 & Lightning 5.4.4. I am now up to 5.7.0 & 5.4.7.

**Comment by jlx84** [comment]
Which version of addon do you have? I hope that I fixed this issue in last version.

**Comment by mwsasser** [comment]
It's version 2.0.  I don't see an update available.  Is it on a different site?

**Comment by jlx84** [comment]
No, v2.0 is the last version I released. I just hoped that I fixed the bug already... can you please describe concrete steps to reproduce the bug? And also the settings of the addon?

**Comment by mwsasser** [comment]
If I open the calendar, the highlighted tab is the previous month.  
If I click a future month, the calendar is correct but it highlights the previous month's tab.

![image](https://user-images.githubusercontent.com/7670483/39369740-b95d5670-4a02-11e8-9431-775e080834b9.png)

**Comment by Jacek63** [comment]
Yes, !!  This is still happening. I'm on version 2.1 and Thunderbird 60. Extremely annoying. Here is the screen shot. After selecting correct month tab it jumps right back and highlights wrong tab.Could you please fix it?
![bad tabs](https://user-images.githubusercontent.com/43253355/45516367-80355880-b770-11e8-8e96-33995cb64527.jpg)

**Comment by mwsasser** [comment]
Agreed, it's still messed up.  Please fix it!

**Comment by lysek** [comment]
Sorry guys, I am not able to replicate that behavior -- I do not say that the bug does not exist, just that it is extremely difficult to fix it if I can't see it. I made a fresh install of Thunderbird 60 with Lightning and my addon and it worked OK.

- Does the addon show correct month when you change the date using arrow buttons over the tabs?
- Do you have some other addons installed (besides lightning and my addon)?
- What is your timezone?
- Is the bug only random or does it happen all the time, or does it happen after particular action, or does it affect only a concrete month?

**Comment by jlx84** [comment]
Sorry guys, I am not able to replicate that behavior -- I do not say that the bug does not exist, just that it is extremely difficult to fix it if I can't see it. I made a fresh install of Thunderbird 60 with Lightning and my addon and it worked OK.

- Does the addon show correct month when you change the date using arrow buttons over the tabs?
- Do you have some other addons installed (besides lightning and my addon)?
- What is your timezone?
- Is the bug only random or does it happen all the time, or does it happen after particular action, or does it affect only a concrete month?

**Comment by mwsasser** [comment]
Hopefully my email response will help you find that pesky bug.

**Comment by jlx84** [comment]
I did not received any email yet - please resend to jlx@seznam.cz.

**Comment by tunefish** [comment]
I can confirm this bug, it only occurs when the Lightning Calendar is configured to use UTC-x timezones.

I created a PR (#5) that resolves this issue, with major changes to the code though.

**Comment by mwsasser** [comment]
Nice.  When can we see the update @jlx84?

**Comment by jlx84** [comment]
Thank you @tunefish. I expected that the bug is time-zone related but I did not have time to fix it yet.
I made a xpi package for testing purposes here: https://github.com/jlx84/lightning-calendar-tabs/releases/tag/2.2-beta (Download it in FF using right mouse button and select "Save link as")
You can install the addon manually in Thunderbird addon manager (button with gear icon). I will test it on my Windows PC tomorrow and then I will release it.

**Comment by jlx84** [comment]
I just uploaded the addon to mozilla addons page.

**Comment by mwsasser** [comment]
Well that's odd.  "This add-on is not compatible with your version of Thunderbird."

**Comment by jlx84** [comment]
Addon is compatible with Thunderbird 59 and 60. I had to make some changes to make it compatible with new Thunderbird versions earlier this year. Older Thunderbird versions are not supported since version 2.1 of my addon. This version is 2.2.

**Comment by mwsasser** [comment]
Oh... my Thunderbird hadn't updated to 64 bit.  Funny what prompts you to remember.   

Thanks for taking this bug seriously.

**Comment by mwsasser** [comment]
With today's Thunderbird update to 60.3.0, I can confirm the bug is gone.

Thanks for fixing it!
